### PR TITLE
Add cleanup function and catch SIGINT

### PR DESCRIPTION
**Pull request by nadavsinai**

### CODE REVIEW

**Comment by L42y** [comment]
Could you please not to change the identation level?

**Comment by L42y** [comment]
@nadavsinai ping

**Comment by nadavsinai** [comment]
sorry about, i also could have reset and redone it but was easier to add another commit, I'll rebase if you are really bothered by it

**Comment by nadavsinai** [comment]
@L42y ping

**Comment by L42y** [comment]
sorry about the delay, thanks!

**Pull request merged**
